import { MigrationInterface, QueryRunner } from "typeorm";

export class InitKaSchema1783782609882 implements MigrationInterface {
    name = 'InitKaSchema1783782609882'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // uuid_generate_v4() defaults below require uuid-ossp; created here so the
        // migration is self-sufficient regardless of TypeORM's installExtensions.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "hospitals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "arabName" character varying(100) NOT NULL, "engName" character varying(100) NOT NULL, "location" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02738c80d71453bc3e369a01766" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "diagnoses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "icdCode" character varying(255) NOT NULL, "icdName" character varying(500) NOT NULL, "neuroLogName" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d1bfabf423f99c537817e6ad244" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proc_cpts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "alphaCode" character varying(10) NOT NULL, "numCode" character varying(10) NOT NULL, "description" character varying(500) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ed7854d94254a53fd5b4fde08df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "arab_procs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "alphaCode" character varying(10) NOT NULL, "numCode" character varying(255) NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7b203caafcd406d87b2c55fb560" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "main_diags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(200) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_780824fd7b407100aaadb1be515" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cal_surgs_gender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TABLE "cal_surgs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timeStamp" TIMESTAMP NOT NULL, "patientName" character varying(255) NOT NULL, "patientDob" date NOT NULL, "gender" "public"."cal_surgs_gender_enum" NOT NULL, "hospitalId" uuid NOT NULL, "arabProcId" uuid, "procDate" date NOT NULL, "google_uid" character varying(255), "formLink" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_879c7111f16fbd1f4af09c9bab6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."candidates_rank_enum" AS ENUM('professor', 'assistant professor', 'lecturer', 'assistant lecturer', 'resident', 'guest', 'specialist', 'other', 'none')`);
        await queryRunner.query(`CREATE TYPE "public"."candidates_regdeg_enum" AS ENUM('msc', 'doctor of medicine (md)', 'egyptian fellowship', 'self registration', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."candidates_role_enum" AS ENUM('superAdmin', 'instituteAdmin', 'supervisor', 'clerk', 'candidate')`);
        await queryRunner.query(`CREATE TABLE "candidates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timeStamp" TIMESTAMP, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "regNum" character varying(50) NOT NULL, "phoneNum" character varying(50) NOT NULL, "nationality" character varying(100) NOT NULL, "rank" "public"."candidates_rank_enum" NOT NULL, "regDeg" "public"."candidates_regdeg_enum", "google_uid" character varying(255), "approved" boolean NOT NULL DEFAULT false, "role" "public"."candidates_role_enum" NOT NULL DEFAULT 'candidate', "termsAcceptedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c0de76a18c2a505ceb016746822" UNIQUE ("email"), CONSTRAINT "PK_140681296bf033ab1eb95288abb" PRIMARY KEY ("id")); COMMENT ON COLUMN "candidates"."termsAcceptedAt" IS 'Timestamp when user accepted Terms of Service'`);
        await queryRunner.query(`CREATE TYPE "public"."supervisors_role_enum" AS ENUM('superAdmin', 'instituteAdmin', 'supervisor', 'clerk', 'candidate')`);
        await queryRunner.query(`CREATE TYPE "public"."supervisors_position_enum" AS ENUM('Professor', 'Assistant Professor', 'Lecturer', 'Assistant Lecturer', 'Guest Doctor', 'Consultant', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "supervisors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "phoneNum" character varying(50) NOT NULL, "approved" boolean NOT NULL DEFAULT false, "role" "public"."supervisors_role_enum" NOT NULL DEFAULT 'supervisor', "canValidate" boolean DEFAULT true, "canValClin" boolean NOT NULL DEFAULT false, "position" "public"."supervisors_position_enum" DEFAULT 'unknown', "termsAcceptedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c8b3b355d7a05ca06f4189040aa" UNIQUE ("email"), CONSTRAINT "PK_7c262062450a70e6f1b9f861232" PRIMARY KEY ("id")); COMMENT ON COLUMN "supervisors"."termsAcceptedAt" IS 'Timestamp when user accepted Terms of Service'`);
        await queryRunner.query(`CREATE TYPE "public"."institute_admins_role_enum" AS ENUM('superAdmin', 'instituteAdmin', 'supervisor', 'clerk', 'candidate')`);
        await queryRunner.query(`CREATE TABLE "institute_admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "phoneNum" character varying(50) NOT NULL, "approved" boolean NOT NULL DEFAULT true, "role" "public"."institute_admins_role_enum" NOT NULL DEFAULT 'instituteAdmin', "termsAcceptedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dfb6572388ad4a913c315407cf4" UNIQUE ("email"), CONSTRAINT "PK_ebe7f8fb39578e0638b1670aa85" PRIMARY KEY ("id")); COMMENT ON COLUMN "institute_admins"."termsAcceptedAt" IS 'Timestamp when user accepted Terms of Service'`);
        await queryRunner.query(`CREATE TYPE "public"."super_admins_role_enum" AS ENUM('superAdmin', 'instituteAdmin', 'supervisor', 'clerk', 'candidate')`);
        await queryRunner.query(`CREATE TABLE "super_admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "phoneNum" character varying(50) NOT NULL, "approved" boolean NOT NULL DEFAULT true, "role" "public"."super_admins_role_enum" NOT NULL DEFAULT 'superAdmin', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9719b4228e14e28a8253cb108f2" UNIQUE ("email"), CONSTRAINT "PK_466d3b6370f0695b22d664e9dff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."submissions_submissiontype_enum" AS ENUM('candidate', 'supervisor')`);
        await queryRunner.query(`CREATE TYPE "public"."submissions_substatus_enum" AS ENUM('approved', 'pending', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timeStamp" TIMESTAMP NOT NULL, "submissionType" "public"."submissions_submissiontype_enum" NOT NULL DEFAULT 'candidate', "candDocId" uuid, "procDocId" uuid NOT NULL, "supervisorDocId" uuid NOT NULL, "roleInSurg" character varying(100) NOT NULL, "assRoleDesc" text, "otherSurgRank" character varying(100) NOT NULL, "otherSurgName" character varying(255) NOT NULL, "isItRevSurg" boolean NOT NULL, "preOpClinCond" text, "insUsed" character varying(1000) NOT NULL, "consUsed" character varying(1000) NOT NULL, "consDetails" text, "mainDiagDocId" uuid NOT NULL, "subGoogleUid" character varying(255), "subStatus" "public"."submissions_substatus_enum" NOT NULL DEFAULT 'pending', "review" text, "reviewedAt" TIMESTAMP, "reviewedBy" character(36), "diagnosisName" json NOT NULL, "procedureName" json NOT NULL, "surgNotes" text, "IntEvents" text, "spOrCran" character varying(50), "pos" character varying(50), "approach" character varying(255), "clinPres" text, "region" character varying(50), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0fd98c7736b161d481c5a9caa5e" UNIQUE ("subGoogleUid"), CONSTRAINT "PK_10b3be95b8b2fb1e482e07d706b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lectures_level_enum" AS ENUM('msc', 'md')`);
        await queryRunner.query(`CREATE TABLE "lectures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lectureTitle" character varying(255) NOT NULL, "google_uid" character varying(255), "mainTopic" character varying(255) NOT NULL, "level" "public"."lectures_level_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fdab57099292bd106710e5cca3b" UNIQUE ("google_uid"), CONSTRAINT "PK_0fbf04287eb4e401af19caf7677" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "journals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "journalTitle" character varying(255) NOT NULL, "pdfLink" text NOT NULL, "google_uid" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_aeb583178509816aea9bee94109" UNIQUE ("google_uid"), CONSTRAINT "PK_157a30136385dd81cdd19111380" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "confs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "confTitle" character varying(255) NOT NULL, "google_uid" character varying(255) NOT NULL, "presenterId" uuid NOT NULL, "date" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_748742df6d1ffae9be2b355e169" UNIQUE ("google_uid"), CONSTRAINT "PK_bd685be805b87dd422a2a81fe64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."event_attendance_addedbyrole_enum" AS ENUM('instituteAdmin', 'supervisor', 'candidate')`);
        await queryRunner.query(`CREATE TABLE "event_attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventId" uuid NOT NULL, "candidateId" uuid NOT NULL, "addedBy" character(36) NOT NULL, "addedByRole" "public"."event_attendance_addedbyrole_enum" NOT NULL, "flagged" boolean NOT NULL DEFAULT false, "flaggedBy" character(36), "flaggedAt" TIMESTAMP, "points" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f8b37ee4567724d40d0ed38d7f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7b316a812e1531db982df8a3d5" ON "event_attendance" ("eventId", "candidateId") `);
        await queryRunner.query(`CREATE TYPE "public"."events_type_enum" AS ENUM('lecture', 'journal', 'conf')`);
        await queryRunner.query(`CREATE TYPE "public"."events_status_enum" AS ENUM('booked', 'held', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."events_type_enum" NOT NULL, "lectureId" uuid, "journalId" uuid, "confId" uuid, "dateTime" TIMESTAMP NOT NULL, "location" character varying(255) NOT NULL, "presenterId" character(36) NOT NULL, "status" "public"."events_status_enum" NOT NULL DEFAULT 'booked', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."password_reset_tokens_userrole_enum" AS ENUM('candidate', 'supervisor', 'superAdmin', 'instituteAdmin')`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character(36) NOT NULL, "userRole" "public"."password_reset_tokens_userrole_enum" NOT NULL, "token" character varying(255) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "used" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab673f0e63eac966762155508ee" UNIQUE ("token"), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f75f11ca4ed69b941336c5d0e3" ON "password_reset_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6a19d4b4f6c62dcd29daa497e" ON "password_reset_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ab673f0e63eac966762155508e" ON "password_reset_tokens" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."clerks_role_enum" AS ENUM('superAdmin', 'instituteAdmin', 'supervisor', 'clerk', 'candidate')`);
        await queryRunner.query(`CREATE TABLE "clerks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "fullName" character varying(255) NOT NULL, "phoneNum" character varying(50) NOT NULL, "approved" boolean NOT NULL DEFAULT false, "role" "public"."clerks_role_enum" NOT NULL DEFAULT 'clerk', "termsAcceptedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d6b6447114e9af54cc775e04491" UNIQUE ("email"), CONSTRAINT "PK_01a88fc3f1655c036722741bd1b" PRIMARY KEY ("id")); COMMENT ON COLUMN "clerks"."termsAcceptedAt" IS 'Timestamp when user accepted Terms of Service'`);
        await queryRunner.query(`CREATE TABLE "additional_questions" ("mainDiagDocId" character(36) NOT NULL, "spOrCran" smallint NOT NULL DEFAULT '0', "pos" smallint NOT NULL DEFAULT '0', "approach" smallint NOT NULL DEFAULT '0', "region" smallint NOT NULL DEFAULT '0', "clinPres" smallint NOT NULL DEFAULT '0', "intEvents" smallint NOT NULL DEFAULT '0', CONSTRAINT "PK_bba11aa68e8fb10c20d005d7ac5" PRIMARY KEY ("mainDiagDocId"))`);
        await queryRunner.query(`CREATE TABLE "consumables" ("id" character(36) NOT NULL, "consumables" character varying(100) NOT NULL, CONSTRAINT "PK_88ce43ef80ea7ac74b91dbd8614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipment" ("id" character(36) NOT NULL, "equipment" character varying(100) NOT NULL, CONSTRAINT "PK_0722e1b9d6eb19f5874c1678740" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "positions" ("id" character(36) NOT NULL, "position" character varying(50) NOT NULL, CONSTRAINT "PK_17e4e62ccd5749b289ae3fae6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "approaches" ("id" character(36) NOT NULL, "approach" character varying(50) NOT NULL, CONSTRAINT "PK_33056a43cb3c3ce64ef2962743d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "regions" ("id" character(36) NOT NULL, "region" character varying(50) NOT NULL, CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."clinical_sub_typeca_enum" AS ENUM('clinical round', 'outpatient clinic', 'workshop', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."clinical_sub_substatus_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "clinical_sub" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candDocId" uuid NOT NULL, "supervisorDocId" uuid NOT NULL, "dateCA" date NOT NULL, "typeCA" "public"."clinical_sub_typeca_enum" NOT NULL, "description" character varying(2000) NOT NULL DEFAULT '', "subStatus" "public"."clinical_sub_substatus_enum" NOT NULL DEFAULT 'pending', "review" text, "reviewedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5ccb4871706d503d47ab6b05c88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."whatsapp_sessions_linked_role_enum" AS ENUM('candidate', 'supervisor', 'unknown')`);
        await queryRunner.query(`CREATE TABLE "whatsapp_sessions" ("id" BIGSERIAL NOT NULL, "wa_from" character varying(32) NOT NULL, "linked_user_id" character(36), "linked_role" "public"."whatsapp_sessions_linked_role_enum" NOT NULL DEFAULT 'unknown', "linked_candidate_id" character(36), "linked_supervisor_id" character(36), "conversation_state" character varying(64) NOT NULL, "context_json" text, "expires_at" TIMESTAMP(3), "created_at" TIMESTAMP(3) NOT NULL DEFAULT now(), "updated_at" TIMESTAMP(3) NOT NULL DEFAULT now(), CONSTRAINT "UQ_928fbc6f9de712f6c28e5b31c42" UNIQUE ("wa_from"), CONSTRAINT "PK_3d45009c99e71c709c8587ae4d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "main_diag_diagnoses" ("mainDiagId" uuid NOT NULL, "diagnosisId" uuid NOT NULL, CONSTRAINT "PK_c48591106a7d1d2560223e6f4f7" PRIMARY KEY ("mainDiagId", "diagnosisId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b39be0f49baa99812a8c4be885" ON "main_diag_diagnoses" ("mainDiagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7c134c7a2540c9f231415a646" ON "main_diag_diagnoses" ("diagnosisId") `);
        await queryRunner.query(`CREATE TABLE "main_diag_procs" ("mainDiagId" uuid NOT NULL, "procCptId" uuid NOT NULL, CONSTRAINT "PK_c17ef3b1628e0860639ca90f805" PRIMARY KEY ("mainDiagId", "procCptId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f5cc043d7afa02a99eeea825fb" ON "main_diag_procs" ("mainDiagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_33458b5d64791c73e2d88ac829" ON "main_diag_procs" ("procCptId") `);
        await queryRunner.query(`CREATE TABLE "submission_proc_cpts" ("submissionId" uuid NOT NULL, "procCptId" uuid NOT NULL, CONSTRAINT "PK_db1332116a1b36e15323083c003" PRIMARY KEY ("submissionId", "procCptId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2af8ff21afff6a4404d079f9b7" ON "submission_proc_cpts" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3d49e2896856d2f2e308c4c15" ON "submission_proc_cpts" ("procCptId") `);
        await queryRunner.query(`CREATE TABLE "submission_icds" ("submissionId" uuid NOT NULL, "icdId" uuid NOT NULL, CONSTRAINT "PK_eb42af7c22441218448a0c881f6" PRIMARY KEY ("submissionId", "icdId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0753ccfd2c1b5c92a534ea1f61" ON "submission_icds" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f441b2b0a84ed9b9406b8a439" ON "submission_icds" ("icdId") `);
        await queryRunner.query(`ALTER TABLE "cal_surgs" ADD CONSTRAINT "FK_9afb981d29509d4ecffaedc5ba5" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cal_surgs" ADD CONSTRAINT "FK_41335c8d6a533c782640bae52d7" FOREIGN KEY ("arabProcId") REFERENCES "arab_procs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_d300c982cabd502d329084bd2f4" FOREIGN KEY ("candDocId") REFERENCES "candidates"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_4ba79d57f559573b287b913e6d7" FOREIGN KEY ("procDocId") REFERENCES "cal_surgs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_4856b80b80565797b433db97184" FOREIGN KEY ("supervisorDocId") REFERENCES "supervisors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submissions" ADD CONSTRAINT "FK_f16f937d0f3a9b4d5e9d3de9ad0" FOREIGN KEY ("mainDiagDocId") REFERENCES "main_diags"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "confs" ADD CONSTRAINT "FK_7eede1c602bce39748971edca51" FOREIGN KEY ("presenterId") REFERENCES "supervisors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_attendance" ADD CONSTRAINT "FK_c8a944f7a30ca4af88684cfc6eb" FOREIGN KEY ("eventId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_attendance" ADD CONSTRAINT "FK_f8d3d9eb97e8b89f472a61bb14a" FOREIGN KEY ("candidateId") REFERENCES "candidates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_b69b135f46f94cfb46472d892ea" FOREIGN KEY ("lectureId") REFERENCES "lectures"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_62599359ff551a4b835b1ece5d0" FOREIGN KEY ("journalId") REFERENCES "journals"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_db286854f3270ab520e44421d56" FOREIGN KEY ("confId") REFERENCES "confs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_sub" ADD CONSTRAINT "FK_7184b6dc398a57476a67a24a13c" FOREIGN KEY ("candDocId") REFERENCES "candidates"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_sub" ADD CONSTRAINT "FK_a6962701e6fb19efd0c951e47f7" FOREIGN KEY ("supervisorDocId") REFERENCES "supervisors"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "main_diag_diagnoses" ADD CONSTRAINT "FK_b39be0f49baa99812a8c4be885c" FOREIGN KEY ("mainDiagId") REFERENCES "main_diags"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "main_diag_diagnoses" ADD CONSTRAINT "FK_f7c134c7a2540c9f231415a646e" FOREIGN KEY ("diagnosisId") REFERENCES "diagnoses"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "main_diag_procs" ADD CONSTRAINT "FK_f5cc043d7afa02a99eeea825fb7" FOREIGN KEY ("mainDiagId") REFERENCES "main_diags"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "main_diag_procs" ADD CONSTRAINT "FK_33458b5d64791c73e2d88ac829a" FOREIGN KEY ("procCptId") REFERENCES "proc_cpts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "submission_proc_cpts" ADD CONSTRAINT "FK_2af8ff21afff6a4404d079f9b70" FOREIGN KEY ("submissionId") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "submission_proc_cpts" ADD CONSTRAINT "FK_e3d49e2896856d2f2e308c4c15b" FOREIGN KEY ("procCptId") REFERENCES "proc_cpts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "submission_icds" ADD CONSTRAINT "FK_0753ccfd2c1b5c92a534ea1f616" FOREIGN KEY ("submissionId") REFERENCES "submissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "submission_icds" ADD CONSTRAINT "FK_0f441b2b0a84ed9b9406b8a439b" FOREIGN KEY ("icdId") REFERENCES "diagnoses"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "submission_icds" DROP CONSTRAINT "FK_0f441b2b0a84ed9b9406b8a439b"`);
        await queryRunner.query(`ALTER TABLE "submission_icds" DROP CONSTRAINT "FK_0753ccfd2c1b5c92a534ea1f616"`);
        await queryRunner.query(`ALTER TABLE "submission_proc_cpts" DROP CONSTRAINT "FK_e3d49e2896856d2f2e308c4c15b"`);
        await queryRunner.query(`ALTER TABLE "submission_proc_cpts" DROP CONSTRAINT "FK_2af8ff21afff6a4404d079f9b70"`);
        await queryRunner.query(`ALTER TABLE "main_diag_procs" DROP CONSTRAINT "FK_33458b5d64791c73e2d88ac829a"`);
        await queryRunner.query(`ALTER TABLE "main_diag_procs" DROP CONSTRAINT "FK_f5cc043d7afa02a99eeea825fb7"`);
        await queryRunner.query(`ALTER TABLE "main_diag_diagnoses" DROP CONSTRAINT "FK_f7c134c7a2540c9f231415a646e"`);
        await queryRunner.query(`ALTER TABLE "main_diag_diagnoses" DROP CONSTRAINT "FK_b39be0f49baa99812a8c4be885c"`);
        await queryRunner.query(`ALTER TABLE "clinical_sub" DROP CONSTRAINT "FK_a6962701e6fb19efd0c951e47f7"`);
        await queryRunner.query(`ALTER TABLE "clinical_sub" DROP CONSTRAINT "FK_7184b6dc398a57476a67a24a13c"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_db286854f3270ab520e44421d56"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_62599359ff551a4b835b1ece5d0"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_b69b135f46f94cfb46472d892ea"`);
        await queryRunner.query(`ALTER TABLE "event_attendance" DROP CONSTRAINT "FK_f8d3d9eb97e8b89f472a61bb14a"`);
        await queryRunner.query(`ALTER TABLE "event_attendance" DROP CONSTRAINT "FK_c8a944f7a30ca4af88684cfc6eb"`);
        await queryRunner.query(`ALTER TABLE "confs" DROP CONSTRAINT "FK_7eede1c602bce39748971edca51"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_f16f937d0f3a9b4d5e9d3de9ad0"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_4856b80b80565797b433db97184"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_4ba79d57f559573b287b913e6d7"`);
        await queryRunner.query(`ALTER TABLE "submissions" DROP CONSTRAINT "FK_d300c982cabd502d329084bd2f4"`);
        await queryRunner.query(`ALTER TABLE "cal_surgs" DROP CONSTRAINT "FK_41335c8d6a533c782640bae52d7"`);
        await queryRunner.query(`ALTER TABLE "cal_surgs" DROP CONSTRAINT "FK_9afb981d29509d4ecffaedc5ba5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f441b2b0a84ed9b9406b8a439"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0753ccfd2c1b5c92a534ea1f61"`);
        await queryRunner.query(`DROP TABLE "submission_icds"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3d49e2896856d2f2e308c4c15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2af8ff21afff6a4404d079f9b7"`);
        await queryRunner.query(`DROP TABLE "submission_proc_cpts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33458b5d64791c73e2d88ac829"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5cc043d7afa02a99eeea825fb"`);
        await queryRunner.query(`DROP TABLE "main_diag_procs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7c134c7a2540c9f231415a646"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b39be0f49baa99812a8c4be885"`);
        await queryRunner.query(`DROP TABLE "main_diag_diagnoses"`);
        await queryRunner.query(`DROP TABLE "whatsapp_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."whatsapp_sessions_linked_role_enum"`);
        await queryRunner.query(`DROP TABLE "clinical_sub"`);
        await queryRunner.query(`DROP TYPE "public"."clinical_sub_substatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."clinical_sub_typeca_enum"`);
        await queryRunner.query(`DROP TABLE "regions"`);
        await queryRunner.query(`DROP TABLE "approaches"`);
        await queryRunner.query(`DROP TABLE "positions"`);
        await queryRunner.query(`DROP TABLE "equipment"`);
        await queryRunner.query(`DROP TABLE "consumables"`);
        await queryRunner.query(`DROP TABLE "additional_questions"`);
        await queryRunner.query(`DROP TABLE "clerks"`);
        await queryRunner.query(`DROP TYPE "public"."clerks_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab673f0e63eac966762155508e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6a19d4b4f6c62dcd29daa497e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f75f11ca4ed69b941336c5d0e3"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."password_reset_tokens_userrole_enum"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TYPE "public"."events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b316a812e1531db982df8a3d5"`);
        await queryRunner.query(`DROP TABLE "event_attendance"`);
        await queryRunner.query(`DROP TYPE "public"."event_attendance_addedbyrole_enum"`);
        await queryRunner.query(`DROP TABLE "confs"`);
        await queryRunner.query(`DROP TABLE "journals"`);
        await queryRunner.query(`DROP TABLE "lectures"`);
        await queryRunner.query(`DROP TYPE "public"."lectures_level_enum"`);
        await queryRunner.query(`DROP TABLE "submissions"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_substatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."submissions_submissiontype_enum"`);
        await queryRunner.query(`DROP TABLE "super_admins"`);
        await queryRunner.query(`DROP TYPE "public"."super_admins_role_enum"`);
        await queryRunner.query(`DROP TABLE "institute_admins"`);
        await queryRunner.query(`DROP TYPE "public"."institute_admins_role_enum"`);
        await queryRunner.query(`DROP TABLE "supervisors"`);
        await queryRunner.query(`DROP TYPE "public"."supervisors_position_enum"`);
        await queryRunner.query(`DROP TYPE "public"."supervisors_role_enum"`);
        await queryRunner.query(`DROP TABLE "candidates"`);
        await queryRunner.query(`DROP TYPE "public"."candidates_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."candidates_regdeg_enum"`);
        await queryRunner.query(`DROP TYPE "public"."candidates_rank_enum"`);
        await queryRunner.query(`DROP TABLE "cal_surgs"`);
        await queryRunner.query(`DROP TYPE "public"."cal_surgs_gender_enum"`);
        await queryRunner.query(`DROP TABLE "main_diags"`);
        await queryRunner.query(`DROP TABLE "arab_procs"`);
        await queryRunner.query(`DROP TABLE "proc_cpts"`);
        await queryRunner.query(`DROP TABLE "diagnoses"`);
        await queryRunner.query(`DROP TABLE "hospitals"`);
    }

}
