### Get All InstituteAdmins
# Note: This endpoint requires authentication as InstituteAdmin or SuperAdmin
GET http://localhost:3001/instituteAdmin
Authorization: Bearer YOUR_JWT_TOKEN_HERE

### Get InstituteAdmin by ID
GET http://localhost:3001/instituteAdmin/INSTITUTE_ADMIN_ID_HERE
Authorization: Bearer YOUR_JWT_TOKEN_HERE

