import { MigrationInterface, QueryRunner } from "typeorm";

export class ExtendCtsProcCpts1750000000058 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── 15 new CARD procedures ────────────────────────────────────────────
    await queryRunner.query(`
      INSERT INTO "proc_cpts" ("title","alphaCode","numCode","description","ar_title","ar_description") VALUES
      ('Temporary transvenous pacemaker insertion','CARD','33210-00','Insertion of temporary transvenous pacing electrode(s) for acute complete heart block, sick sinus syndrome, or haemodynamically unstable bradycardia.','تركيب جهاز ضبط النبض المؤقت عبر الوريد','إدخال قطب التحفيز المؤقت عبر الوريد لعلاج الحصار الأذيني البطيني الحاد أو بطء القلب غير المستقر ديناميكياً.'),
      ('Surgical ablation limited (Maze procedure)','CARD','33250-00','Limited surgical ablation of the atrial tissue creating lesions to interrupt re-entrant circuits causing atrial fibrillation or flutter; performed concomitantly with other cardiac surgery.','الاستئصال الحراري الجراحي المحدود (متاهة القلب)','استئصال محدود لنسيج الأذيني جراحياً لإنشاء آفات تقطع دوائر إعادة الدخول المسببة للرجفان أو الرفيف الأذيني؛ يُجرى بالتزامن مع جراحات قلبية أخرى.'),
      ('Surgical ablation extensive (extended Maze)','CARD','33256-00','Extensive surgical ablation creating a complete Maze lesion set in both atria to restore sinus rhythm in long-standing atrial fibrillation, usually combined with mitral valve surgery.','الاستئصال الحراري الجراحي الموسع (متاهة القلب الموسعة)','استئصال جراحي موسع يُنشئ مجموعة آفات متاهة كاملة في الأذينين لاستعادة إيقاع الجيب في الرجفان الأذيني المزمن، ويُجمع عادةً مع جراحة الصمام التاجي.'),
      ('Repair of cardiac wound','CARD','33300-00','Surgical repair of penetrating cardiac injury (stab or gunshot wound) with direct suture of the myocardial laceration under controlled haemostasis; may require partial cardiopulmonary bypass.','ترميم جرح القلب','ترميم جراحي لإصابة قلبية نافذة بالخياطة المباشرة للتمزق العضلي القلبي تحت ضبط النزيف.'),
      ('Closed mitral commissurotomy (without bypass)','CARD','33420-00','Digital or instrument-assisted splitting of fused mitral valve commissures without cardiopulmonary bypass; historically performed for rheumatic mitral stenosis in resource-limited or high-risk settings.','بضع التصاقات الصمام التاجي المغلق (بدون دوران)','فصل التصاقات الصمام التاجي بالإصبع أو الآلات دون دوران دموي خارج الجسم؛ يُستخدم تاريخياً في تضيق الصمام التاجي الروماتيزمي.'),
      ('Left ventricular aneurysm repair','CARD','33542-00','Surgical resection or endoventricular patch repair (Dor procedure) of post-infarction left ventricular aneurysm to restore ventricular geometry, contractility, and reduce arrhythmia burden.','ترميم أم دم البطين الأيسر','استئصال أم دم البطين الأيسر بعد الاحتشاء أو ترميمها بالرقعة الداخلية (عملية دور) لاستعادة هندسة البطين وانقباضيته.'),
      ('Coronary endarterectomy','CARD','33572-00','Surgical removal of atherosclerotic plaque from a diffusely diseased coronary artery to achieve adequate distal runoff prior to bypass grafting; most commonly performed on the right coronary artery.','استئصال باطنة الشريان التاجي','إزالة جراحية للويحة التصلبية من الشريان التاجي المصاب بشكل منتشر لتحسين التدفق البعيد قبل مجازة الشريان.'),
      ('Repair of complete atrioventricular canal defect','CARD','33650-00','Complete repair of AVSD (endocardial cushion defect) including closure of atrial and ventricular septal components and reconstruction of the common AV valve into separate mitral and tricuspid valves under cardiopulmonary bypass.','إصلاح عيب القناة الأذينية البطينية الكاملة','إصلاح كامل لعيب الوسادة الشغافية يشمل إغلاق مكوني الحاجز وإعادة بناء الصمام الأذيني البطيني المشترك.'),
      ('Pulmonary artery banding','CARD','33690-00','Placement of a constrictive band around the main pulmonary artery to reduce pulmonary blood flow and protect the pulmonary vascular bed in patients with large left-to-right shunts not amenable to early primary repair.','تضييق الشريان الرئوي بالشريط','وضع شريط تضيقي حول الشريان الرئوي الرئيسي للحدّ من التدفق الرئوي وحماية الأوعية الرئوية في الحالات ذات التحويل الكبير من اليسار إلى اليمين.'),
      ('Repair of sinus of Valsalva fistula','CARD','33722-00','Surgical closure of ruptured sinus of Valsalva aneurysm with patch repair under cardiopulmonary bypass; may drain into right atrium, right ventricle, or pulmonary artery.','ترميم ناسور جيب فالسالفا','إغلاق جراحي لأم دم جيب فالسالفا المتمزقة بالرقعة تحت دوران خارج الجسم.'),
      ('Fontan procedure','CARD','33766-00','Total cavopulmonary connection (lateral tunnel or extracardiac conduit) routing all systemic venous return directly to the pulmonary artery, bypassing the functional single ventricle in the final stage of staged palliation.','عملية فونتان','توصيل كلي للأوردة الكبيرة بالشريان الرئوي (نفق جانبي أو موصل خارج القلب) في المرحلة النهائية من التلطيف المرحلي للقلب الأحادي البطين.'),
      ('Heart-lung transplantation','CARD','33945-00','En bloc transplantation of both heart and lungs for end-stage cardiopulmonary failure not amenable to isolated heart or lung transplantation; includes tracheal anastomosis and right atrial anastomosis.','زرع القلب والرئتين معاً','زرع كتلي للقلب والرئتين في قصور القلب والرئة النهائي غير القابل للعلاج بالزرع المنفرد.'),
      ('Intra-aortic balloon pump insertion','CARD','33970-00','Percutaneous or open insertion of intra-aortic balloon pump via femoral artery for counterpulsation in cardiogenic shock, severe LV dysfunction, or as a bridge to cardiac surgery or transplantation.','إدخال مضخة البالون داخل الأبهر','إدخال مضخة البالون داخل الأبهر عبر الشريان الفخذي لمضادة النبض في الصدمة القلبية أو الخلل الشديد في البطين الأيسر.'),
      ('Right ventricular assist device (RVAD) implantation','CARD','33976-00','Implantation of mechanical circulatory support device for the right ventricle in isolated right ventricular failure, post-LVAD RV failure, or post-transplant primary graft dysfunction.','تركيب جهاز مساعدة البطين الأيمن','تركيب جهاز دعم الدورة الدموية الميكانيكية للبطين الأيمن في قصور البطين الأيمن المعزول أو الإخفاق الأولي بعد الزرع.'),
      ('Total artificial heart implantation','CARD','33980-00','Implantation of a total artificial heart (biventricular pneumatic device) as a bridge to transplantation in patients with biventricular failure refractory to LVAD or RVAD support.','تركيب القلب الاصطناعي الكلي','تركيب قلب اصطناعي كلي (جهاز ثنائي البطين) كجسر للزرع في قصور البطينين المقاوم للعلاج.')
      ON CONFLICT ("alphaCode","numCode") DO NOTHING
    `);

    // ── 13 new THOR procedures ────────────────────────────────────────────
    await queryRunner.query(`
      INSERT INTO "proc_cpts" ("title","alphaCode","numCode","description","ar_title","ar_description") VALUES
      ('Chest wall resection with rib(s)','THOR','19260-00','Resection of chest wall including one or more ribs for primary chest wall tumour, chondrosarcoma, or soft tissue sarcoma; may include mesh reconstruction of the thoracic defect.','استئصال جدار الصدر مع الأضلاع','استئصال جدار الصدر مع ضلع أو أكثر لورم حميد أو خبيث، قد يشمل إعادة بناء الجدار بالشبكة الاصطناعية.'),
      ('Pectus carinatum repair','THOR','21743-00','Open surgical correction of pectus carinatum (pigeon chest) by subperichondrial resection of deformed costal cartilages and sternal osteotomy (Ravitch-type technique).','إصلاح الصدر الكيلي','تصحيح الصدر الكيلي جراحياً بالاستئصال تحت الغضروفي للغضاريف الضلعية المشوهة وبضع القص.'),
      ('Tracheal resection and anastomosis (intrathoracic)','THOR','31780-00','Resection of intrathoracic tracheal segment for stenosis, tracheomalacia, or primary tracheal tumour followed by primary end-to-end anastomosis; may require median sternotomy or right thoracotomy approach.','استئصال القصبة الهوائية ومفاغرتها (داخل الصدر)','استئصال قطعة من القصبة الهوائية الصدرية لتضيق أو ورم أولي يليها مفاغرة طرف لطرف.'),
      ('Thoracoplasty','THOR','32035-00','Resection of multiple ribs to collapse the chest wall over a chronically infected pleural space (empyema thoracis) or destroyed lung that cannot be fully decorticated; rarely performed in the modern era.','رأب القفص الصدري','استئصال أضلاع متعددة لانطواء جدار الصدر فوق تجويف الدبيلة المزمنة أو الرئة المدمرة التي لا يمكن تقشيرها.'),
      ('Open pleural biopsy','THOR','32098-00','Open surgical biopsy of the parietal or visceral pleura for definitive histological diagnosis of pleural disease including mesothelioma, metastatic deposits, or granulomatous pleuritis.','خزعة الجنب المفتوحة','خزعة جراحية مفتوحة من الجنب الجداري أو الحشوي للتشخيص النسيجي القاطع لأمراض الجنب بما فيها الورم المتوسطي.'),
      ('Thoracentesis','THOR','32420-00','Needle aspiration of pleural fluid for diagnosis or therapeutic relief of large pleural effusion; performed under local anaesthesia with or without ultrasound guidance.','بزل الصدر','شفط إبري للسائل الجنبي للتشخيص أو لتخفيف انصباب جنبي كبير تحت التخدير الموضعي.'),
      ('Sleeve resection (bronchoplastic lobectomy)','THOR','32490-00','Anatomic lobectomy combined with circular resection of the bronchial sleeve at the lobar orifice and end-to-end bronchial anastomosis to preserve lung parenchyma; preferred over pneumonectomy in central tumours.','استئصال الفص مع الكم القصبي','استئصال تشريحي للفص مع استئصال حلقي للكم القصبي ومفاغرة قصبية طرف لطرف للحفاظ على حمة الرئة في الأورام المركزية.'),
      ('Superior sulcus (Pancoast) tumour resection','THOR','32503-00','En-bloc resection of superior sulcus lung tumour with involved chest wall structures (ribs, subclavian vessels, brachial plexus components) via posterior or anterior approach after induction chemoradiotherapy.','استئصال ورم المنطقة القمية (باسنكوست)','استئصال كتلي لورم الأخدود العلوي مع هياكل جدار الصدر المشاركة عبر نهج خلفي أو أمامي بعد العلاج الكيميائي الإشعاعي التحضيري.'),
      ('Single lung transplantation','THOR','32851-00','Replacement of one diseased lung with a donor lung including bronchial anastomosis, pulmonary artery anastomosis, and pulmonary vein anastomosis; for end-stage pulmonary fibrosis, COPD, or pulmonary hypertension.','زرع رئة واحدة','استبدال رئة مريضة بأخرى من متبرع يشمل مفاغرة القصبة والشريان والوريد الرئوي لمرض الرئة الخلالي النهائي أو ارتفاع الضغط الرئوي.'),
      ('Mediastinoscopy with biopsy','THOR','39000-00','Cervical mediastinoscopy for sampling of paratracheal, tracheobronchial, and subcarinal lymph nodes for staging of lung cancer or diagnosis of mediastinal disease (lymphoma, sarcoidosis).','تنظير المنصف مع الخزعة','تنظير عنقي للمنصف لأخذ عينات من العقد اللمفية للتحديد المرحلي لسرطان الرئة أو تشخيص أمراض المنصف.'),
      ('Resection of mediastinal cyst','THOR','39200-00','Surgical excision of congenital or acquired mediastinal cyst (bronchogenic, pericardial, enteric, or thymic cyst) via thoracotomy or VATS to relieve compression and confirm histology.','استئصال كيسة المنصف','استئصال جراحي للكيسة المنصفية الخلقية أو المكتسبة بالجراحة المفتوحة أو المنظار لتخفيف الضغط وتأكيد التشخيص النسيجي.'),
      ('Upper GI endoscopy (EGD)','THOR','43235-00','Flexible oesophago-gastro-duodenoscopy for evaluation of oesophageal malignancy, achalasia, peptic stricture, or Barrett oesophagus relevant to thoracic surgical planning.','تنظير الجهاز الهضمي العلوي (المعدة والمريء والاثني عشر)','تنظير مرن للمريء والمعدة والاثني عشر لتقييم أمراض المريء الخبيثة أو حالات الارتخاء العضلي والتضيق الهضمي ذات الصلة بالتخطيط الجراحي الصدري.'),
      ('Upper GI endoscopy with biopsy','THOR','43239-00','Flexible oesophago-gastro-duodenoscopy with biopsy for histological confirmation of oesophageal or gastric lesions prior to surgical resection.','تنظير الجهاز الهضمي العلوي مع الخزعة','تنظير مرن للجهاز الهضمي العلوي مع أخذ خزعة للتأكيد النسيجي للآفات المريئية أو المعدية قبل الاستئصال الجراحي.')
      ON CONFLICT ("alphaCode","numCode") DO NOTHING
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const cardCodes = ['33210-00','33250-00','33256-00','33300-00','33420-00','33542-00','33572-00','33650-00','33690-00','33722-00','33766-00','33945-00','33970-00','33976-00','33980-00'];
    const thorCodes = ['19260-00','21743-00','31780-00','32035-00','32098-00','32420-00','32490-00','32503-00','32851-00','39000-00','39200-00','43235-00','43239-00'];

    for (const code of cardCodes) {
      await queryRunner.query(`DELETE FROM "proc_cpts" WHERE "alphaCode"='CARD' AND "numCode"=$1`, [code]);
    }
    for (const code of thorCodes) {
      await queryRunner.query(`DELETE FROM "proc_cpts" WHERE "alphaCode"='THOR' AND "numCode"=$1`, [code]);
    }
  }
}
