import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * MFS (Maxillofacial Surgery) academic lectures — transcribed from the ISCP Oral and Maxillofacial
 * Surgery Curriculum (Aug 2021), Appendix 2 "Oral and Maxillofacial Surgery Syllabus". Reference
 * cited in MEDICAL_CODE_AUDITS/MFS/LECTURES_MFS.md.
 *
 * Part 3 (final): Restoration of Aesthetic Form & Function, Cleft Lip & Palate, Craniofacial, Dentoalveolar lectures.
 *
 * The syllabus's 12 clinical MODULES map to lecture_topics; each module's competence-graded
 * syllabus topic-lines map to lectures (numbered <topic>.1.<n>). The generic "Common Content Module"
 * (Core Surgical Training Phase-1 basic science, shared across all surgical specialties) is excluded
 * as non-OMFS-specific (documented in the audit file). Faithful transcription — nothing invented.
 * **`level` is NULL** on every row: the ISCP P2/P3/SI competence markers are training-phase tiers,
 * NOT the Egyptian MSc/MD construct, so level is left NULL (sourced later) not guessed. Bilingual.
 */
export class AuthorMfsLecturesRestorationCleftCraniofacialDentoalveolar1750000000210 implements MigrationInterface {
  name = "AuthorMfsLecturesRestorationCleftCraniofacialDentoalveolar1750000000210";

  // topic → its index in the 12-topic list (for numbering <idx>.1.<n>)
  private readonly TOPIC_INDEX: Record<string, number> = {
    "restoration of normal aesthetic form and function": 9,
    "cleft lip and palate": 10,
    "craniofacial": 11,
    "dentoalveolar": 12,
  };

  // section 1 = KNOWLEDGE/CLINICAL. { topic, en, ar }
  private readonly LECTURES: Array<{ topic: string; en: string; ar: string }> = [
    // ── 9. restoration of normal aesthetic form and function ──
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy of the structures of the head and neck", ar: "التشريح التطبيقي لبنى الرأس والرقبة" },
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy of the soft tissues of the head and neck", ar: "التشريح التطبيقي للأنسجة الرخوة للرأس والرقبة" },
    { topic: "restoration of normal aesthetic form and function", en: "intra-oral approaches to the facial skeleton", ar: "المداخل داخل الفموية للهيكل الوجهي" },
    { topic: "restoration of normal aesthetic form and function", en: "extra-oral approaches to the facial skeleton", ar: "المداخل خارج الفموية للهيكل الوجهي" },
    { topic: "restoration of normal aesthetic form and function", en: "demonstrate an understanding of the aesthetic units of the face as they relate to normal form", ar: "إظهار فهم للوحدات الجمالية للوجه من حيث علاقتها بالشكل الطبيعي" },
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy of the nose including extra and intra-nasal access", ar: "التشريح التطبيقي للأنف بما في ذلك الوصول خارج وداخل الأنف" },
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy of the ears and classification of ear deformity", ar: "التشريح التطبيقي للأذنين وتصنيف تشوه الأذن" },
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy of the eyelids", ar: "التشريح التطبيقي للجفنين" },
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy and variations of the facial nerve", ar: "التشريح التطبيقي وتباينات العصب الوجهي" },
    { topic: "restoration of normal aesthetic form and function", en: "supporting ligaments of the facial skin and relation to bone", ar: "الأربطة الداعمة لجلد الوجه وعلاقتها بالعظم" },
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy of the fascial planes of the face", ar: "التشريح التطبيقي للمستويات اللفافية للوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "applied anatomy of the facial muscles", ar: "التشريح التطبيقي لعضلات الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "physiology of structures of the face including nose, eyes, eyelids, skin", ar: "فسيولوجيا بنى الوجه بما في ذلك الأنف والعينان والجفنان والجلد" },
    { topic: "restoration of normal aesthetic form and function", en: "physiology of age-related changes to skin and facial norms", ar: "فسيولوجيا التغيرات المرتبطة بالعمر في الجلد ومعايير الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "principles of wound healing and scar formation", ar: "مبادئ التئام الجروح وتكوّن الندبات" },
    { topic: "restoration of normal aesthetic form and function", en: "physiology of different skin types", ar: "فسيولوجيا أنواع الجلد المختلفة" },
    { topic: "restoration of normal aesthetic form and function", en: "pathology associated with facial asymmetries", ar: "الباثولوجيا المرتبطة بعدم تناظر الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "sun exposure-related changes to skin and facial norms", ar: "التغيرات المرتبطة بالتعرض للشمس في الجلد ومعايير الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "effect of laser / light treatments on the skin", ar: "تأثير علاجات الليزر / الضوء على الجلد" },
    { topic: "restoration of normal aesthetic form and function", en: "assessment of patient’s reasons for seeking treatment within context of psychology", ar: "تقييم أسباب المريض لطلب العلاج ضمن السياق النفسي" },
    { topic: "restoration of normal aesthetic form and function", en: "recognition of the need for formal psychological assessment", ar: "التعرف على الحاجة لتقييم نفسي رسمي" },
    { topic: "restoration of normal aesthetic form and function", en: "recognition and counselling of patients requiring psychological input", ar: "التعرف على المرضى المحتاجين لمدخلات نفسية وإرشادهم" },
    { topic: "restoration of normal aesthetic form and function", en: "pharmacology of neurotoxin agents", ar: "علم أدوية عوامل السموم العصبية" },
    { topic: "restoration of normal aesthetic form and function", en: "indications, methods and limitations/complications of fat grafting to facial defects", ar: "دواعي وطرق وقيود/مضاعفات ترقيع الدهون لعيوب الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "knowledge of different filler preparations available, their indications (licensed and non licensed) and management of complications of treatment", ar: "معرفة مستحضرات الحشو المختلفة المتاحة ودواعيها (المرخصة وغير المرخصة) وتدبير مضاعفات العلاج" },
    { topic: "restoration of normal aesthetic form and function", en: "types and indications for laser therapy and complications of treatment", ar: "أنواع ودواعي العلاج بالليزر ومضاعفات العلاج" },
    { topic: "restoration of normal aesthetic form and function", en: "knowledge of different skin formations for skin stimulation and rejuvenation", ar: "معرفة تركيبات الجلد المختلفة لتحفيز الجلد وتجديده" },
    { topic: "restoration of normal aesthetic form and function", en: "formulations, applications and management of complications of chemical peeling agents", ar: "تركيبات وتطبيقات وتدبير مضاعفات عوامل التقشير الكيميائي" },
    { topic: "restoration of normal aesthetic form and function", en: "indications for skin/scar revision and potential complications", ar: "دواعي مراجعة الجلد/الندبة والمضاعفات المحتملة" },
    { topic: "restoration of normal aesthetic form and function", en: "indications, limitations and complications of minimal access approach to facial ptosis/palsy", ar: "دواعي وقيود ومضاعفات مدخل الوصول الأدنى لتدلي/شلل الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "non-surgical management of ear deformity", ar: "التدبير غير الجراحي لتشوه الأذن" },
    { topic: "restoration of normal aesthetic form and function", en: "assessment and diagnosis of patterns of facial appearance including age related to changes", ar: "تقييم وتشخيص أنماط مظهر الوجه بما في ذلك التغيرات المرتبطة بالعمر" },
    { topic: "restoration of normal aesthetic form and function", en: "assessment and diagnosis of facial mis-proportion", ar: "تقييم وتشخيص عدم تناسب الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "assessment of occlusion, dental aesthetics and restorative need", ar: "تقييم الإطباق والجماليات السنية والحاجة الترميمية" },
    { topic: "restoration of normal aesthetic form and function", en: "assessment and diagnosis of facial asymmetry", ar: "تقييم وتشخيص عدم تناظر الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "principles of management of facial asymmetry including the role of orthognathic surgery and camouflage procedures", ar: "مبادئ تدبير عدم تناظر الوجه بما في ذلك دور جراحة تقويم الفكين وإجراءات التمويه" },
    { topic: "restoration of normal aesthetic form and function", en: "assessment and diagnosis of deformities of the nose", ar: "تقييم وتشخيص تشوهات الأنف" },
    { topic: "restoration of normal aesthetic form and function", en: "clinical record keeping including photography", ar: "حفظ السجلات السريرية بما في ذلك التصوير الفوتوغرافي" },
    { topic: "restoration of normal aesthetic form and function", en: "role of ct and virtual imaging in diagnosis and treatment planning", ar: "دور التصوير المقطعي والافتراضي في التشخيص وتخطيط العلاج" },
    { topic: "restoration of normal aesthetic form and function", en: "assess and produce a management plan for non-surgical treatment", ar: "تقييم ووضع خطة تدبير للعلاج غير الجراحي" },
    { topic: "restoration of normal aesthetic form and function", en: "role of facial implants for the management of facial asymmetry and restoration of facial form", ar: "دور الغرسات الوجهية في تدبير عدم تناظر الوجه واستعادة الشكل الوجهي" },
    { topic: "restoration of normal aesthetic form and function", en: "role of virtual planning and use of custom designed implants for restoration of facial form", ar: "دور التخطيط الافتراضي واستخدام الغرسات المصممة خصيصًا لاستعادة الشكل الوجهي" },
    { topic: "restoration of normal aesthetic form and function", en: "assessment and diagnosis of the facial norms in gender reassignment surgery", ar: "تقييم وتشخيص معايير الوجه في جراحة تغيير الجنس" },
    { topic: "restoration of normal aesthetic form and function", en: "recognition & management of complications of surgery to restore facial/nasal form and function", ar: "التعرف على وتدبير مضاعفات جراحة استعادة الشكل والوظيفة الوجهية/الأنفية" },
    { topic: "restoration of normal aesthetic form and function", en: "moral and medico-legal competence", ar: "الكفاءة الأخلاقية والطبية القانونية" },
    { topic: "restoration of normal aesthetic form and function", en: "life-threatening haemorrhage (sphenopalatine artery ligation, nasal packing)", ar: "النزف المهدد للحياة (ربط الشريان الوتدي الحنكي والحشو الأنفي)" },
    { topic: "restoration of normal aesthetic form and function", en: "sight-threatening trauma (post-operative)", ar: "الإصابة المهددة للبصر (بعد الجراحة)" },
    { topic: "restoration of normal aesthetic form and function", en: "local anaesthesia and use of topical agents", ar: "التخدير الموضعي واستخدام العوامل الموضعية" },
    { topic: "restoration of normal aesthetic form and function", en: "correction of nasal deformity including bone, cartilage and soft tissue structures", ar: "تصحيح تشوه الأنف بما في ذلك بنى العظم والغضروف والأنسجة الرخوة" },
    { topic: "restoration of normal aesthetic form and function", en: "septal surgery to restore normal form and function", ar: "جراحة الحاجز لاستعادة الشكل والوظيفة الطبيعية" },
    { topic: "restoration of normal aesthetic form and function", en: "harvest cartilage graft from nasal septum, ear and costochondral junction", ar: "حصاد طعم غضروفي من الحاجز الأنفي والأذن والوصل الضلعي الغضروفي" },
    { topic: "restoration of normal aesthetic form and function", en: "harvest temporal fascia", ar: "حصاد اللفافة الصدغية" },
    { topic: "restoration of normal aesthetic form and function", en: "harvest calvarial vault bone", ar: "حصاد عظم قبة القحف" },
    { topic: "restoration of normal aesthetic form and function", en: "correction of ear deformity including otoplasty", ar: "تصحيح تشوه الأذن بما في ذلك رأب الأذن" },
    { topic: "restoration of normal aesthetic form and function", en: "direct correction of brow ptosis", ar: "التصحيح المباشر لتدلي الحاجب" },
    { topic: "restoration of normal aesthetic form and function", en: "endoscopic correction of brow ptosis", ar: "التصحيح التنظيري لتدلي الحاجب" },
    { topic: "restoration of normal aesthetic form and function", en: "upper blepharoplasty", ar: "رأب الجفن العلوي" },
    { topic: "restoration of normal aesthetic form and function", en: "lower blepharoplasty", ar: "رأب الجفن السفلي" },
    { topic: "restoration of normal aesthetic form and function", en: "lateral canthopexy", ar: "تثبيت الملتقى الجفني الجانبي" },
    { topic: "restoration of normal aesthetic form and function", en: "facelift for facial ptosis/palsy", ar: "شد الوجه لتدلي/شلل الوجه" },
    { topic: "restoration of normal aesthetic form and function", en: "neck lift/platysmaplasty for correction of ptosis of the submental region", ar: "شد الرقبة/رأب العضلة الجلدية لتصحيح تدلي المنطقة تحت الذقن" },
    { topic: "restoration of normal aesthetic form and function", en: "lipectomy for correction of facial form", ar: "استئصال الدهون لتصحيح الشكل الوجهي" },
    { topic: "restoration of normal aesthetic form and function", en: "fat grafting", ar: "ترقيع الدهون" },
    { topic: "restoration of normal aesthetic form and function", en: "insertion of implants to correct facial form", ar: "إدخال الغرسات لتصحيح الشكل الوجهي" },
    { topic: "restoration of normal aesthetic form and function", en: "cheiloplasty/augmention/lip reconstruction", ar: "رأب الشفة/التكبير/إعادة بناء الشفة" },
    { topic: "restoration of normal aesthetic form and function", en: "genioplasty", ar: "رأب الذقن" },
    { topic: "restoration of normal aesthetic form and function", en: "re-contouring of forehead for correction facial norm/feminisation surgery", ar: "إعادة تشكيل الجبهة لتصحيح معيار الوجه / جراحة التأنيث" },
    { topic: "restoration of normal aesthetic form and function", en: "re-contouring of mandible for correction of facial norm/feminisation surgery", ar: "إعادة تشكيل الفك السفلي لتصحيح معيار الوجه / جراحة التأنيث" },
    { topic: "restoration of normal aesthetic form and function", en: "hairline reshaping for correction of facial norm/feminisation surgery", ar: "إعادة تشكيل خط الشعر لتصحيح معيار الوجه / جراحة التأنيث" },
    // ── 10. cleft lip and palate ──
    { topic: "cleft lip and palate", en: "applied anatomy of the hard tissues of the head and neck", ar: "التشريح التطبيقي للأنسجة الصلبة للرأس والرقبة" },
    { topic: "cleft lip and palate", en: "applied anatomy of the soft tissues of the head and neck", ar: "التشريح التطبيقي للأنسجة الرخوة للرأس والرقبة" },
    { topic: "cleft lip and palate", en: "intra and extra oral approaches to the facial skeleton", ar: "المداخل داخل وخارج الفموية للهيكل الوجهي" },
    { topic: "cleft lip and palate", en: "open and closed approaches to the nose", ar: "المداخل المفتوحة والمغلقة للأنف" },
    { topic: "cleft lip and palate", en: "anatomy and embryology of cleft lip and palate anomaly", ar: "تشريح وأجنّة شذوذ الشفة الأرنبية وشق الحنك" },
    { topic: "cleft lip and palate", en: "anatomy of ear and temporal bone", ar: "تشريح الأذن والعظم الصدغي" },
    { topic: "cleft lip and palate", en: "protocols for repair of cleft lip and palate", ar: "بروتوكولات إصلاح الشفة الأرنبية وشق الحنك" },
    { topic: "cleft lip and palate", en: "historical perspective of cleft lip and palate repair", ar: "المنظور التاريخي لإصلاح الشفة الأرنبية وشق الحنك" },
    { topic: "cleft lip and palate", en: "dental development", ar: "التطور السني" },
    { topic: "cleft lip and palate", en: "pathological anatomy, embryology and basic genetics of facial clefting and associated anomalies.", ar: "التشريح المرضي والأجنّة والوراثة الأساسية للشقوق الوجهية والشذوذات المرافقة" },
    { topic: "cleft lip and palate", en: "pathology of speech of cleft lip and palate", ar: "باثولوجيا النطق في الشفة الأرنبية وشق الحنك" },
    { topic: "cleft lip and palate", en: "pathological anatomy of the repaired cleft palate", ar: "التشريح المرضي لشق الحنك المُصلَح" },
    { topic: "cleft lip and palate", en: "pathological physiology of after cleft repair", ar: "الفيزيولوجيا المرضية بعد إصلاح الشق" },
    { topic: "cleft lip and palate", en: "physiology of speech", ar: "فسيولوجيا النطق" },
    { topic: "cleft lip and palate", en: "physiology of hearing", ar: "فسيولوجيا السمع" },
    { topic: "cleft lip and palate", en: "physiology of breathing", ar: "فسيولوجيا التنفس" },
    { topic: "cleft lip and palate", en: "physiology of feeding and swallowing", ar: "فسيولوجيا التغذية والبلع" },
    { topic: "cleft lip and palate", en: "physiology of velopharyngeal dysfunction", ar: "فسيولوجيا الخلل الحنكي البلعومي" },
    { topic: "cleft lip and palate", en: "principles, indications and interpretation of imaging modalities", ar: "مبادئ ودواعي وتفسير طرائق التصوير" },
    { topic: "cleft lip and palate", en: "audiogram and tympanometry study, understanding the principles of brain stem evoked response audiometry", ar: "دراسة مخطط السمع وقياس الطبل، وفهم مبادئ قياس السمع بالاستجابة المستثارة لجذع الدماغ" },
    { topic: "cleft lip and palate", en: "diagnosis of genetic conditions associated with cleft", ar: "تشخيص الحالات الوراثية المرتبطة بالشق" },
    { topic: "cleft lip and palate", en: "principles, indications of nasenedoscopy and videofluoscopy for speech problems", ar: "مبادئ ودواعي تنظير الأنف والتصوير الفيديوي بالتألق لمشاكل النطق" },
    { topic: "cleft lip and palate", en: "principles, indications for orthodontic and restorative management", ar: "مبادئ ودواعي التدبير التقويمي والترميمي" },
    { topic: "cleft lip and palate", en: "recognition of facial and jaw deformity resulting from cleft lip and palate", ar: "التعرف على تشوه الوجه والفك الناتج عن الشفة الأرنبية وشق الحنك" },
    { topic: "cleft lip and palate", en: "classification of cleft lip", ar: "تصنيف الشفة الأرنبية" },
    { topic: "cleft lip and palate", en: "classification of cleft palate", ar: "تصنيف شق الحنك" },
    { topic: "cleft lip and palate", en: "classification of facial clefts", ar: "تصنيف الشقوق الوجهية" },
    { topic: "cleft lip and palate", en: "cleft lip and palate repair protocols (including historic and international variations)", ar: "بروتوكولات إصلاح الشفة الأرنبية وشق الحنك (بما في ذلك التباينات التاريخية والدولية)" },
    { topic: "cleft lip and palate", en: "techniques for cleft lip & nose repair", ar: "تقنيات إصلاح الشفة الأرنبية والأنف" },
    { topic: "cleft lip and palate", en: "national guidelines for the diagnosis, treatment and follow up of cleft patients", ar: "الإرشادات الوطنية لتشخيص وعلاج ومتابعة مرضى الشق" },
    { topic: "cleft lip and palate", en: "pain and pain relief in the cleft and paediatric patient", ar: "الألم وتسكينه لدى مريض الشق والأطفال" },
    { topic: "cleft lip and palate", en: "surgeons, dentists, nursing, speech therapy, anaesthetists, psychologists etc.", ar: "الجراحون وأطباء الأسنان والتمريض وعلاج النطق وأطباء التخدير وعلماء النفس وغيرهم" },
    { topic: "cleft lip and palate", en: "psychological effects and management of the cleft patient within an mdt environment", ar: "الآثار النفسية وتدبير مريض الشق ضمن بيئة الفريق متعدد التخصصات" },
    { topic: "cleft lip and palate", en: "lifelong psychological effects of cleft lip and palate", ar: "الآثار النفسية مدى الحياة للشفة الأرنبية وشق الحنك" },
    { topic: "cleft lip and palate", en: "biomechanics of musculoskeletal tissues", ar: "الميكانيكا الحيوية للأنسجة العضلية الهيكلية" },
    { topic: "cleft lip and palate", en: "biomechanics of skeletal fixation and distraction osteogenesis", ar: "الميكانيكا الحيوية للتثبيت الهيكلي وتكوين العظم بالإطالة" },
    { topic: "cleft lip and palate", en: "properties of biomaterials including plates, autografts, allografts, sutures, implant", ar: "خصائص المواد الحيوية بما في ذلك الصفائح والطعوم الذاتية والخيفية والخيوط والغرسات" },
    { topic: "cleft lip and palate", en: "factors contributing to and prediction of potential complications and risks", ar: "العوامل المساهمة في المضاعفات والمخاطر المحتملة والتنبؤ بها" },
    { topic: "cleft lip and palate", en: "management strategies for potential complications", ar: "استراتيجيات تدبير المضاعفات المحتملة" },
    { topic: "cleft lip and palate", en: "acute airway obstruction", ar: "انسداد مجرى الهواء الحاد" },
    { topic: "cleft lip and palate", en: "life-threatening haemorrhage", ar: "النزف المهدد للحياة" },
    { topic: "cleft lip and palate", en: "assess and diagnosis patient’s and relatives concerns", ar: "تقييم وتشخيص مخاوف المريض وأقاربه" },
    { topic: "cleft lip and palate", en: "assess and diagnose lip and nose disability", ar: "تقييم وتشخيص إعاقة الشفة والأنف" },
    { topic: "cleft lip and palate", en: "assess and diagnose the primary and secondary dentition", ar: "تقييم وتشخيص الإسنان الأولي والثانوي" },
    { topic: "cleft lip and palate", en: "assess and diagnose the need for alveolar bone graft in palatal fistula", ar: "تقييم وتشخيص الحاجة لطعم العظم السنخي في الناسور الحنكي" },
    { topic: "cleft lip and palate", en: "mdt", ar: "الفريق متعدد التخصصات" },
    { topic: "cleft lip and palate", en: "nasendoscopy", ar: "تنظير الأنف" },
    { topic: "cleft lip and palate", en: "videofluroscopy", ar: "التصوير الفيديوي بالتألق" },
    { topic: "cleft lip and palate", en: "management of the airway", ar: "تدبير مجرى الهواء" },
    { topic: "cleft lip and palate", en: "investigation of speech problems", ar: "فحص مشاكل النطق" },
    { topic: "cleft lip and palate", en: "moral and medico-legal competence", ar: "الكفاءة الأخلاقية والطبية القانونية" },
    { topic: "cleft lip and palate", en: "pre and post-operative patient/child undergoing cleft surgery including assessment for anaesthetic risk factors, postoperative fluid management, antibiotic prescribing", ar: "المريض/الطفل قبل وبعد جراحة الشق بما في ذلك تقييم عوامل خطر التخدير وتدبير السوائل بعد الجراحة ووصف المضادات الحيوية" },
    { topic: "cleft lip and palate", en: "manage naso-pharyngeal airway in the peri- and post- operative environment, and post-operatively,", ar: "تدبير مجرى الهواء الأنفي البلعومي في بيئة ما حول وبعد الجراحة" },
    { topic: "cleft lip and palate", en: "repair of incomplete cleft of the lip", ar: "إصلاح الشق غير الكامل للشفة" },
    { topic: "cleft lip and palate", en: "repair of complete cleft lip utilising currently recognised standard techniques", ar: "إصلاح الشفة الأرنبية الكاملة باستخدام التقنيات القياسية المعترف بها حاليًا" },
    { topic: "cleft lip and palate", en: "repair of cleft palate", ar: "إصلاح شق الحنك" },
    { topic: "cleft lip and palate", en: "re-repair of cleft palate", ar: "إعادة إصلاح شق الحنك" },
    { topic: "cleft lip and palate", en: "furlow palatoplasty", ar: "رأب الحنك بطريقة فورلو" },
    { topic: "cleft lip and palate", en: "buccal flaps for surgery to improve speech", ar: "الرفارف الشدقية لجراحة تحسين النطق" },
    { topic: "cleft lip and palate", en: "orticochea pharyngoplasty", ar: "رأب البلعوم بطريقة أورتيكوكيا" },
    { topic: "cleft lip and palate", en: "pharyngeal flap", ar: "الرفرف البلعومي" },
    { topic: "cleft lip and palate", en: "alveolar bone graft", ar: "طعم العظم السنخي" },
    { topic: "cleft lip and palate", en: "revision of cleft lip", ar: "مراجعة الشفة الأرنبية" },
    { topic: "cleft lip and palate", en: "cleft rhinoplasty", ar: "رأب الأنف الشقي" },
    { topic: "cleft lip and palate", en: "orthognathic surgery in cleft patients", ar: "جراحة تقويم الفكين لدى مرضى الشق" },
    // ── 11. craniofacial ──
    { topic: "craniofacial", en: "principles of the cf mdt process, team members and national referral pathways", ar: "مبادئ عملية الفريق متعدد التخصصات القحفي الوجهي وأعضاء الفريق ومسارات الإحالة الوطنية" },
    { topic: "craniofacial", en: "speech and language assessments of cf conditions + national pathways", ar: "تقييمات النطق واللغة للحالات القحفية الوجهية + المسارات الوطنية" },
    { topic: "craniofacial", en: "psychology involvement and assessments of cf conditions + national pathways", ar: "إشراك علم النفس وتقييمات الحالات القحفية الوجهية + المسارات الوطنية" },
    { topic: "craniofacial", en: "applied anatomy of the hard tissues of the skull, head and neck", ar: "التشريح التطبيقي للأنسجة الصلبة للجمجمة والرأس والرقبة" },
    { topic: "craniofacial", en: "applied anatomy of the soft tissues of the skull, brain, head and neck", ar: "التشريح التطبيقي للأنسجة الرخوة للجمجمة والمخ والرأس والرقبة" },
    { topic: "craniofacial", en: "coronal approaches to the skull", ar: "المداخل التاجية للجمجمة" },
    { topic: "craniofacial", en: "transfacial approaches to the facial skeleton", ar: "المداخل عبر الوجه للهيكل الوجهي" },
    { topic: "craniofacial", en: "applied embryology to facial / skull skeleton relating to cf conditions", ar: "الأجنّة التطبيقية للهيكل الوجهي/القحفي المتعلقة بالحالات القحفية الوجهية" },
    { topic: "craniofacial", en: "principles of wound healing", ar: "مبادئ التئام الجروح" },
    { topic: "craniofacial", en: "principles of bone healing", ar: "مبادئ التئام العظم" },
    { topic: "craniofacial", en: "principles of nerve healing", ar: "مبادئ التئام العصب" },
    { topic: "craniofacial", en: "metabolic and immunological response to trauma", ar: "الاستجابة الأيضية والمناعية للإصابة" },
    { topic: "craniofacial", en: "pathology / genetics of craniofacial microsomia + branchial arch disorders + congenital deformity", ar: "باثولوجيا/وراثة صغر نصف الوجه القحفي + اضطرابات القوس الخيشومي + التشوه الخلقي" },
    { topic: "craniofacial", en: "pathology of facial clefting / encephaloceles / dermoid cysts", ar: "باثولوجيا الشقوق الوجهية / القيلات الدماغية / الكيسات الجلدانية" },
    { topic: "craniofacial", en: "pathology of paediatric facial and skull (hard and soft tissue) tumours", ar: "باثولوجيا أورام الوجه والجمجمة (الأنسجة الصلبة والرخوة) لدى الأطفال" },
    { topic: "craniofacial", en: "principles and genetics of neurofibromatosis / facial lipomatosis", ar: "مبادئ ووراثة الورم العصبي الليفي / الورم الشحمي الوجهي" },
    { topic: "craniofacial", en: "pathology of chiari malformation", ar: "باثولوجيا تشوه كياري" },
    { topic: "craniofacial", en: "physiology of sight", ar: "فسيولوجيا الإبصار" },
    { topic: "craniofacial", en: "physiology of the sinus physiology / drainage", ar: "فسيولوجيا الجيوب / التصريف" },
    { topic: "craniofacial", en: "physiology of the naso-lacrimal system", ar: "فسيولوجيا الجهاز الأنفي الدمعي" },
    { topic: "craniofacial", en: "physiology of csf flow", ar: "فسيولوجيا تدفق السائل الدماغي الشوكي" },
    { topic: "craniofacial", en: "physiology of tissue expansion", ar: "فسيولوجيا توسيع الأنسجة" },
    { topic: "craniofacial", en: "principles, indications and interpretation of imaging modalities", ar: "مبادئ ودواعي وتفسير طرائق التصوير" },
    { topic: "craniofacial", en: "principles, indications and interpretation of electrophysiological investigations", ar: "مبادئ ودواعي وتفسير الفحوص الفيزيولوجية الكهربية" },
    { topic: "craniofacial", en: "principles and indications of sleep studies", ar: "مبادئ ودواعي دراسات النوم" },
    { topic: "craniofacial", en: "principles and indications of swallow assessments", ar: "مبادئ ودواعي تقييمات البلع" },
    { topic: "craniofacial", en: "classification / associated features / treatment protocols of syndromic craniosynostosis + pathway for different stages of life", ar: "تصنيف / الملامح المرافقة / بروتوكولات علاج تعظم الدروز الباكر المتلازمي + المسار لمختلف مراحل الحياة" },
    { topic: "craniofacial", en: "classification / treatment of non-syndromic craniosynostosis", ar: "تصنيف / علاج تعظم الدروز الباكر غير المتلازمي" },
    { topic: "craniofacial", en: "classification / treatment of benign deformational plagiocephaly + torticollis", ar: "تصنيف / علاج الرأس المائل التشوهي الحميد + الصعر" },
    { topic: "craniofacial", en: "classification / treatment of facial clefting", ar: "تصنيف / علاج الشقوق الوجهية" },
    { topic: "craniofacial", en: "classification / pathology / treatment of vascular malformations", ar: "تصنيف / باثولوجيا / علاج التشوهات الوعائية" },
    { topic: "craniofacial", en: "classification / treatment and reconstruction of cranial nerve deficiencies / defects", ar: "تصنيف / علاج وإعادة بناء نقائص/عيوب الأعصاب القحفية" },
    { topic: "craniofacial", en: "classification / treatment protocols of facial overgrowth conditions", ar: "تصنيف / بروتوكولات علاج حالات فرط نمو الوجه" },
    { topic: "craniofacial", en: "classification / treatment of orbital malposition conditions", ar: "تصنيف / علاج حالات سوء موضع الحجاج" },
    { topic: "craniofacial", en: "pain and pain relief in the paediatric and adult craniofacial patient", ar: "الألم وتسكينه لدى مريض الوجه القحفي من الأطفال والبالغين" },
    { topic: "craniofacial", en: "biomechanics of musculoskeletal tissues", ar: "الميكانيكا الحيوية للأنسجة العضلية الهيكلية" },
    { topic: "craniofacial", en: "biomechanics of resorbable / non-resorbable fracture + bone fixation", ar: "الميكانيكا الحيوية لتثبيت الكسور والعظم القابل / غير القابل للامتصاص" },
    { topic: "craniofacial", en: "properties of biomaterials including plates, autografts, allografts, sutures", ar: "خصائص المواد الحيوية بما في ذلك الصفائح والطعوم الذاتية والطعوم الخيفية والخيوط الجراحية" },
    { topic: "craniofacial", en: "factors contributing to and prediction of potential complications and risks", ar: "العوامل المساهمة في المضاعفات والمخاطر المحتملة والتنبؤ بها" },
    { topic: "craniofacial", en: "management strategies for potential complications", ar: "استراتيجيات تدبير المضاعفات المحتملة" },
    { topic: "craniofacial", en: "acute airway obstruction in the craniofacial patient", ar: "انسداد مجرى الهواء الحاد لدى المريض القحفي الوجهي" },
    { topic: "craniofacial", en: "retro-bulbar haemorrhage", ar: "النزف خلف المقلة" },
    { topic: "craniofacial", en: "life-threatening haemorrhage", ar: "النزف المهدد للحياة" },
    { topic: "craniofacial", en: "intra-cranial haemorrhage – pre-, intra- and post-operative", ar: "النزف داخل القحف – قبل وأثناء وبعد الجراحة" },
    { topic: "craniofacial", en: "craniofacial (skull and upper face acquired deformity)", ar: "القحفي الوجهي (التشوه المكتسب للجمجمة والوجه العلوي)" },
    { topic: "craniofacial", en: "management of the airway in paediatric and craniofacial patients", ar: "تدبير مجرى الهواء لدى مرضى الأطفال والقحفيين الوجهيين" },
    { topic: "craniofacial", en: "cephalometric diagnosis and planning of craniofacial patients", ar: "التشخيص والتخطيط القياسي القحفي لمرضى الوجه القحفي" },
    { topic: "craniofacial", en: "patient specific planning / virtual treatment planning", ar: "التخطيط الخاص بالمريض / التخطيط العلاجي الافتراضي" },
    { topic: "craniofacial", en: "paediatric emergency life support / resuscitation", ar: "دعم الحياة الطارئ / الإنعاش لدى الأطفال" },
    { topic: "craniofacial", en: "paediatric airway management", ar: "تدبير مجرى الهواء لدى الأطفال" },
    { topic: "craniofacial", en: "paediatric fluid / electrolytes and blood resuscitation / management", ar: "تدبير / إنعاش السوائل والكهارل والدم لدى الأطفال" },
    { topic: "craniofacial", en: "moral and medico-legal competence", ar: "الكفاءة الأخلاقية والطبية القانونية" },
    { topic: "craniofacial", en: "infiltration and nerve blocks for local anaesthesia", ar: "التسريب وحصر الأعصاب للتخدير الموضعي" },
    { topic: "craniofacial", en: "soft tissue wound repair", ar: "إصلاح جرح الأنسجة الرخوة" },
    { topic: "craniofacial", en: "coronal flap", ar: "الرفرف التاجي (الإكليلي)" },
    { topic: "craniofacial", en: "tarsorrhaphy techniques – temporary + permanent", ar: "تقنيات خياطة الجفنين – المؤقتة والدائمة" },
    { topic: "craniofacial", en: "neurovascular tissue repair", ar: "إصلاح النسيج العصبي الوعائي" },
    { topic: "craniofacial", en: "facial cleft / coloboma repair", ar: "إصلاح الشق الوجهي / الثُّلامة" },
    { topic: "craniofacial", en: "fronto-orbital advancement and remodelling", ar: "التقديم الجبهي الحجاجي وإعادة التشكيل" },
    { topic: "craniofacial", en: "strip craniectomy + micro-barrel staving", ar: "استئصال شريطي للقحف + التخديد المجهري" },
    { topic: "craniofacial", en: "total vault remodelling", ar: "إعادة تشكيل القبة القحفية الكلية" },
    { topic: "craniofacial", en: "vault distraction (anterior / posterior)", ar: "إطالة القبة القحفية (الأمامية / الخلفية)" },
    { topic: "craniofacial", en: "le fort 2 / 3 osteotomy", ar: "قطع عظم لوفور 2 / 3" },
    { topic: "craniofacial", en: "monobloc / fronto-facial advancement", ar: "التقديم الأحادي الكتلة / الجبهي الوجهي" },
    { topic: "craniofacial", en: "orbital box osteotomy", ar: "قطع عظم الصندوق الحجاجي" },
    { topic: "craniofacial", en: "frontal bipartition", ar: "التقسيم الجبهي الثنائي" },
    { topic: "craniofacial", en: "encephalocele repair", ar: "إصلاح القيلة الدماغية" },
    { topic: "craniofacial", en: "transcranial dermoid excision", ar: "استئصال الكيسة الجلدانية عبر القحف" },
    { topic: "craniofacial", en: "le fort 1 access to base of skull", ar: "الوصول بلوفور 1 إلى قاعدة الجمجمة" },
    { topic: "craniofacial", en: "mandibular paediatric distraction osteogenesis", ar: "تكوين العظم بالإطالة للفك السفلي لدى الأطفال" },
    { topic: "craniofacial", en: "syndromic rhinoplasty", ar: "رأب الأنف المتلازمي" },
    { topic: "craniofacial", en: "costo-chondral rib harvest", ar: "حصاد الضلع الضلعي الغضروفي" },
    { topic: "craniofacial", en: "autologous ramus-condyle unit / costochondral rib reconstruction", ar: "إعادة بناء وحدة الفرع-اللقمة الذاتية / الضلع الضلعي الغضروفي" },
    { topic: "craniofacial", en: "autologous calvarial grafting", ar: "الترقيع القحفي الذاتي" },
    { topic: "craniofacial", en: "autologous fat grafting", ar: "ترقيع الدهون الذاتي" },
    { topic: "craniofacial", en: "tissue expansion", ar: "توسيع الأنسجة" },
    { topic: "craniofacial", en: "cranioplasty - alloplastic", ar: "رأب القحف - بمادة صناعية" },
    { topic: "craniofacial", en: "facial alloplastic implants / augmentation", ar: "الغرسات الوجهية الصناعية / التكبير" },
    // ── 12. dentoalveolar ──
    { topic: "dentoalveolar", en: "applied anatomy of the hard and dental tissues of the head and neck", ar: "التشريح التطبيقي للأنسجة الصلبة والسنية للرأس والرقبة" },
    { topic: "dentoalveolar", en: "applied anatomy of the soft tissues of the head and neck including potential infection spaces", ar: "التشريح التطبيقي للأنسجة الرخوة للرأس والرقبة بما في ذلك فراغات العدوى المحتملة" },
    { topic: "dentoalveolar", en: "intra-oral approaches to the facial skeleton and soft tissues", ar: "المداخل داخل الفموية للهيكل الوجهي والأنسجة الرخوة" },
    { topic: "dentoalveolar", en: "extra-oral approaches to the facial skeleton", ar: "المداخل خارج الفموية للهيكل الوجهي" },
    { topic: "dentoalveolar", en: "congenital and developmental defects of the dentition", ar: "العيوب الخلقية والتطورية للإسنان" },
    { topic: "dentoalveolar", en: "congenital and developmental bone diseases affecting the maxilla and mandible", ar: "أمراض العظم الخلقية والتطورية المصيبة للفك العلوي والسفلي" },
    { topic: "dentoalveolar", en: "odontogenic pathology of the maxilla and mandible", ar: "الباثولوجيا السنية المنشأ للفك العلوي والسفلي" },
    { topic: "dentoalveolar", en: "non-odontogenic pathology within the maxilla and mandible", ar: "الباثولوجيا غير السنية المنشأ ضمن الفك العلوي والسفلي" },
    { topic: "dentoalveolar", en: "mechanism of infection (dental and non-dental aetiology)", ar: "آلية العدوى (المسببات السنية وغير السنية)" },
    { topic: "dentoalveolar", en: "metabolic and immunological response to infection", ar: "الاستجابة الأيضية والمناعية للعدوى" },
    { topic: "dentoalveolar", en: "physiology of growth", ar: "فسيولوجيا النمو" },
    { topic: "dentoalveolar", en: "physiology of bone", ar: "فسيولوجيا العظم" },
    { topic: "dentoalveolar", en: "physiology of soft tissue, dental and bone healing", ar: "فسيولوجيا التئام الأنسجة الرخوة والسنية والعظمية" },
    { topic: "dentoalveolar", en: "principles and indications and interpretation of imaging modalities", ar: "مبادئ ودواعي وتفسير طرائق التصوير" },
    { topic: "dentoalveolar", en: "classification of nerve injuries", ar: "تصنيف إصابات الأعصاب" },
    { topic: "dentoalveolar", en: "classification of dento-alveolar injuries", ar: "تصنيف الإصابات السنخية السنية" },
    { topic: "dentoalveolar", en: "classification of third molar position including radiological", ar: "تصنيف موضع ضرس العقل بما في ذلك الشعاعي" },
    { topic: "dentoalveolar", en: "classification of occlusal relationships", ar: "تصنيف العلاقات الإطباقية" },
    { topic: "dentoalveolar", en: "analgesic agents", ar: "العوامل المسكنة" },
    { topic: "dentoalveolar", en: "local anaesthetic agents", ar: "عوامل التخدير الموضعي" },
    { topic: "dentoalveolar", en: "psychological effects and management of a patient with congenital or acquired conditions affecting the teeth and supporting structures", ar: "الآثار النفسية وتدبير المريض المصاب بحالات خلقية أو مكتسبة تؤثر على الأسنان والبنى الداعمة" },
    { topic: "dentoalveolar", en: "properties of biomaterials including plates, autografts, allografts, sutures and osseo-integration.", ar: "خصائص المواد الحيوية بما في ذلك الصفائح والطعوم الذاتية والخيفية والخيوط والاندماج العظمي" },
    { topic: "dentoalveolar", en: "properties of local anaesthetics", ar: "خصائص المخدرات الموضعية" },
    { topic: "dentoalveolar", en: "factors contributing to and prediction of potential complications and risks", ar: "العوامل المساهمة في المضاعفات والمخاطر المحتملة والتنبؤ بها" },
    { topic: "dentoalveolar", en: "management strategies for potential complications", ar: "استراتيجيات تدبير المضاعفات المحتملة" },
    { topic: "dentoalveolar", en: "awareness and appropriate use of national guidelines", ar: "الوعي بالإرشادات الوطنية واستخدامها المناسب" },
    { topic: "dentoalveolar", en: "acute airway obstruction", ar: "انسداد مجرى الهواء الحاد" },
    { topic: "dentoalveolar", en: "sepsis and septic shock", ar: "الإنتان والصدمة الإنتانية" },
    { topic: "dentoalveolar", en: "displacement of teeth", ar: "إزاحة الأسنان" },
    { topic: "dentoalveolar", en: "appreciation of restorative dentistry as it relates to the teeth and supporting structures", ar: "إدراك طب الأسنان الترميمي من حيث علاقته بالأسنان والبنى الداعمة" },
    { topic: "dentoalveolar", en: "appreciation of orthodontics as it relates to the teeth and supporting structures", ar: "إدراك تقويم الأسنان من حيث علاقته بالأسنان والبنى الداعمة" },
    { topic: "dentoalveolar", en: "appreciation of special care dentistry as it relates to the teeth and supporting structure", ar: "إدراك طب أسنان الرعاية الخاصة من حيث علاقته بالأسنان والبنى الداعمة" },
    { topic: "dentoalveolar", en: "neurovascular injury", ar: "الإصابة العصبية الوعائية" },
    { topic: "dentoalveolar", en: "dento-alveolar injury", ar: "الإصابة السنخية السنية" },
    { topic: "dentoalveolar", en: "management of the airway", ar: "تدبير مجرى الهواء" },
    { topic: "dentoalveolar", en: "combined orthodontic management of the dentition", ar: "التدبير التقويمي المشترك للإسنان" },
    { topic: "dentoalveolar", en: "combined restorative/periodontal management of dentition", ar: "التدبير الترميمي/اللثوي المشترك للإسنان" },
    { topic: "dentoalveolar", en: "third molar assessment", ar: "تقييم ضرس العقل" },
    { topic: "dentoalveolar", en: "moral and medico-legal competence", ar: "الكفاءة الأخلاقية والطبية القانونية" },
    { topic: "dentoalveolar", en: "infiltration and nerve blocks for local anaesthesia", ar: "التسريب وحصر الأعصاب للتخدير الموضعي" },
    { topic: "dentoalveolar", en: "simple extraction of teeth", ar: "القلع البسيط للأسنان" },
    { topic: "dentoalveolar", en: "surgical removal of retained teeth/roots", ar: "الإزالة الجراحية للأسنان/الجذور المحتبسة" },
    { topic: "dentoalveolar", en: "surgical removal of ectopic/impacted teeth", ar: "الإزالة الجراحية للأسنان المنتبذة/المنطمرة" },
    { topic: "dentoalveolar", en: "surgical removal of impacted wisdom teeth*", ar: "الإزالة الجراحية لأضراس العقل المنطمرة *" },
    { topic: "dentoalveolar", en: "coronectomy of third molars", ar: "استئصال تاج أضراس العقل" },
    { topic: "dentoalveolar", en: "immediate management of oral antral communications", ar: "التدبير الفوري للاتصالات الفموية الجيبية" },
    { topic: "dentoalveolar", en: "management of an oral antral fistula", ar: "تدبير الناسور الفموي الجيبي" },
    { topic: "dentoalveolar", en: "management of an oral cutaneous fistula", ar: "تدبير الناسور الفموي الجلدي" },
    { topic: "dentoalveolar", en: "reduction and splinting of dento-alveolar fractures", ar: "رد وتجبير الكسور السنخية السنية" },
    { topic: "dentoalveolar", en: "harvesting of bone grafts from mandible.", ar: "حصاد طعوم العظم من الفك السفلي" },
    { topic: "dentoalveolar", en: "harvesting of bone grafts from non-jaw sites", ar: "حصاد طعوم العظم من مواقع غير فكية" },
    { topic: "dentoalveolar", en: "pre-prosthetic preparation and prosthetic placement of implants", ar: "التحضير قبل التعويضي ووضع الغرسات التعويضي" },
    { topic: "dentoalveolar", en: "peri-radicular surgery of teeth", ar: "الجراحة حول الذروية للأسنان" },
    { topic: "dentoalveolar", en: "marsupialisation of jaw cysts", ar: "تسقيف كيسات الفك" },
    { topic: "dentoalveolar", en: "enucleation of jaw cysts", ar: "استئصال كيسات الفك" },
    { topic: "dentoalveolar", en: "enucleation of odontogenic and non-odontogenic pathology of the jaws", ar: "استئصال الباثولوجيا السنية وغير السنية المنشأ للفكين" },
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    const q = (s: string) => s.replace(/'/g, "''");
    const topicIndex = new Map(Object.entries(this.TOPIC_INDEX));

    const counters = new Map<string, number>();
    const rows = this.LECTURES.map((l) => {
      const c = topicIndex.get(l.topic)!;
      const n = (counters.get(l.topic) ?? 0) + 1;
      counters.set(l.topic, n);
      const num = `${c}.1.${n}`;
      const ord = c * 1_000_000 + 1_000 + n;
      return `('${q(l.topic)}', '${q(num)}', '${q(l.en)}', '${q(l.ar)}', ${ord})`;
    });
    const batchSize = 50;
    for (let i = 0; i < rows.length; i += batchSize) {
      const batch = rows.slice(i, i + batchSize).join(",\n          ");
      await queryRunner.query(`
        INSERT INTO "lectures" ("topicId", "lectureNumber", "title", "arTitle", "level", "sortOrder")
        SELECT lt."id", v.number, v.title, v.ar, NULL, v.ord
        FROM (VALUES ${batch}) AS v(topic, number, title, ar, ord)
        JOIN "departments" d ON d."code" = 'MFS'
        JOIN "lecture_topics" lt ON lt."departmentId" = d."id" AND lt."title" = v.topic
      `);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM "lectures" lx
      USING "lecture_topics" lt, "departments" d
      WHERE lx."topicId" = lt."id" AND lt."departmentId" = d."id" AND d."code" = 'MFS'
        AND lt."title" IN ('restoration of normal aesthetic form and function', 'cleft lip and palate', 'craniofacial', 'dentoalveolar')
    `);
  }
}
