POST http://localhost:3001/arabProc/createArabProc
Content-Type: application/json

{
    "title": "بذل من اليافوج",
    "alphaCode": "MNR",
    "numCode": "61000",
    "description": "inserting a needle into the cerebral ventricles to withdraw CSF or relieve pressure."
}

POST http://localhost:3001/arabProc/createArabProcFromExternal
Content-Type: application/json

{"row": 12}

POST http://localhost:3001/arabProc/createArabProcFromExternal
Content-Type: application/json

{}