POST http://localhost:3001/arabProc/createArabProc
Content-Type: application/json

{
    "title": "مراجعة صمام اوميا",
    "alphaCode": "VSHN",
    "numCode": "61070",
    "description": "Ommaya valve reservoir check and fluid sampling procedure."
}

POST http://localhost:3001/arabProc/createArabProcFromExternal
Content-Type: application/json

{"row": 12}

POST http://localhost:3001/arabProc/createArabProcFromExternal
Content-Type: application/json

{}