### Get All SuperAdmins
# Note: This endpoint requires authentication as a SuperAdmin
GET http://localhost:3001/superAdmin
Authorization: Bearer YOUR_JWT_TOKEN_HERE

### Get SuperAdmin by ID
GET http://localhost:3001/superAdmin/SUPER_ADMIN_ID_HERE
Authorization: Bearer YOUR_JWT_TOKEN_HERE

